include makefiles/app.mk
include makefiles/api.mk

help:
	@echo "🎯 Commandes disponibles"
	@echo "-------------------------"
	@echo "make app-help         : Aide pour l'app React Native"
	@echo "make api-help         : Aide pour le backend Django"
